delete from ClaimCheck;
delete from CollaborationGroup_User;
delete from CollaborationGroup;
delete from User;
alter table ClaimCheck drop foreign key ClaimCheck_user_id_fk;
alter table ClaimCheck drop index ClaimCheck_user_id_index;
alter table Session drop foreign key Session_user_id_fk;
alter table Session drop index Session_user_id_index;
alter table CollaborationGroup_User drop foreign key CollaborationGroup_User_user_id_index;
alter table CollaborationGroup_User drop index CollaborationGroup_User_user_id_index;
alter table CollaborationGroup drop foreign key CollaborationGroup_user_id_fk;
alter table CollaborationGroup drop index CollaborationGroup_user_id_index;
drop table if exists User;
drop table if exists Company;
create table Company (id varchar(255) not null, name varchar(255), title varchar(255), primary key (id)) ENGINE=InnoDB;
create table User (id varchar(255) not null, firstName varchar(255), lastName varchar(255), language varchar(255), certificate_id varchar(255) not null, verified bit(1) not null, pending bit(1) not null, email varchar(255), password varchar(255), company_id varchar(255), primary key (id)) ENGINE=InnoDB;
alter table User add index User_certificate_index (certificate_id), add constraint User_certificate_fk foreign key (certificate_id) references Certificate (id);
alter table User add index User_email_index (email);
alter table User add index User_company_id_index (company_id);
alter table User add constraint User_company_id_fk foreign key (company_id) references Company (id);
alter table ClaimCheck modify user_id varchar(255) not null;
alter table ClaimCheck add index ClaimCheck_user_id_index (user_id);
alter table ClaimCheck add constraint ClaimCheck_user_id_fk foreign key (user_id) references User (id);
alter table Session modify user_id varchar(255) not null;
alter table Session add index Session_user_id_index (user_id), add constraint Session_user_id_fk foreign key (user_id) references User (id);
alter table CollaborationGroup_User modify user_id varchar(255) not null;
alter table CollaborationGroup_User add index CollaborationGroup_User_user_id_index (user_id), add constraint CollaborationGroup_User_user_id_index foreign key (user_id) references User (id);
alter table CollaborationGroup modify user_id varchar(255) not null;
alter table CollaborationGroup add index CollaborationGroup_user_id_index (user_id), add constraint CollaborationGroup_user_id_fk foreign key (user_id) references User (id);

